# Generated by Django 5.0.2 on 2024-03-25 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderDetaol',
            new_name='OrderDetail',
        ),
        migrations.AlterModelTable(
            name='order',
            table='order',
        ),
        migrations.AlterModelTable(
            name='orderdetail',
            table='order_detail',
        ),
    ]
