# Generated by Django 5.0.2 on 2024-04-03 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_orderdetaol_orderdetail_alter_order_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_token',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
