# Generated by Django 5.0.2 on 2024-04-03 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_order_token_orderdetail_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
