# Generated by Django 5.0.2 on 2024-04-03 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderdetail_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='status',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
