# Generated by Django 5.0.2 on 2024-04-04 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_orderdetail_status_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_token',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
